- platform: sysfs_gpio
  pins:
    129:
      name: motion
- platform: mqtt
  name: "Датчик движения гараж"
  state_topic: "sensor/garage/motion"
  payload_on: "True"
  payload_off: "False"
  device_class: motion