# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

homeassistant:
  name: kuzindom
  latitude: !secret latitude
  longitude: !secret longitude
  unit_system: metric
  time_zone: Europe/Moscow
  customize: !include customize.yaml

http:
  base_url: !secret domain
  trusted_proxies: !secret proxy
  use_x_forwarded_for: true
  ip_ban_enabled: true
  login_attempts_threshold: 5

# Text to speech
tts:
  - platform: google_translate
group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
light: !include light.yaml
sensor: !include sensor.yaml
binary_sensor: !include binary_sensor.yaml
switch: !include switch.yaml

mqtt:
  broker: 127.0.0.1
  discovery: true
  discovery_prefix: homeassistant

#logger:
#   default: debug

samsungtv_H:
    name: SamsungTV
    host: !secret samsung_tv_ip
    port: 8000
    session_id: !secret samsung_tv_id
    session_key: !secret samsung_tv_key

google_assistant:
  project_id: !secret project_id
  service_account: !include google_service.json
  report_state: true
  exposed_domains:
    - switch
    - light
    - sensor
  entity_config: !include google_assistant_entity.yaml

#  - platform: group
#    name: Kitchen Lights
#    entities:
#      - light.Kitchen_work_zone
#      - light.Kitchen_on_table
#  - platform: group
#    name: Mihail Lights
#    entities:
#      - light.Mihail_2_lamps
#      - light.Mihail_4_lamps